version: "3.8"

services:
  mysql:
    image: mysql:8.0.20
    container_name: mysql-form-app
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: formmanagement
    ports:
      - "3307:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: form-management
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-form-app:3306/formmanagement?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
