services:
  db:
    image: mysql:8.0.20
    container_name: mysql-form-app
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: formmanagement
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - spring_network

  app:
    build: .
    container_name: form-management
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    networks:
      - spring_network

networks:
  spring_network:
    driver: bridge

volumes:
  db_data: